### ISSUE TITLE
Series list imported from Trakt does not refresh after initial configuration

### ISSUE THREAD

**Issue by CorentinWicht** [Flexget/webui#185]
### Steps to reproduce:
- Step 1: Create a Trakt.tv account and a list
- Step 2: Use [FlexGet cookbook example](https://flexget.com/Cookbook/Series/trakt_manager) to import the list
- Step 3: Add a new show to your Trakt.tv list
- Step 4: FlexGet webUI Series tab does not get refreshed and the new show does not show up/is not downloaded

#### Config:
```yaml
web_server:
    bind: 0.0.0.0
    port: 8290
    web_ui: yes

templates:
  torrentclient:
    transmission:
      host: localhost
      port: 9091
      username: /variables/transmission/username
      password: /variables/transmission/password
  tv:
    configure_series:
      settings:
        # Configure all the series options to your taste
        quality: 720p-1080p !cam !ts
        path: /volume1/Media/Series/{{series_name}}/Season {{series_season}}/  # This will sort your downloads if you are using one of the output plugins which supports it
        identified_by: ep
      from:
        trakt_list:
          account: MyAccount
          list: TV Shows
          type: shows
    no_entries_ok: yes

tasks:
  # This task will look for episodes you have added to your `TV Shows` list at trakt.
  # It will set the `begin` series option for that show, then remove the episode and re-add
  # it to your `TV Shows` list as a show.
  follow-series:
    seen: local
    priority: 1
    trakt_list:
      account: MyAccount
      list: TV Shows
      type: shows
    accept_all: yes
    set_series_begin: yes
    list_remove:
      - trakt_list:
          account: MyAccount
          list: TV Shows
          type: episodes
    list_add:
      - trakt_list:
          account: MyAccount
          list: TV Shows
          type: shows
  
  Download-ENG:
    priority: 2
    discover:
      what:
        - next_series_episodes:
            from_start: yes
      from:
        - limetorrents:
            category: tv  
        - piratebay:
            category: tv
    template:
      - torrentclient
      - tv
      
  Download-FR:
    priority: 2
    rss: RSSFEEDLINK
    template:
      - torrentclient
      - tv
      
schedules:
  - tasks: '*'
    interval:
      minutes: 2
```

#### Log:
<details>
 <summary>(click to expand)</summary>

```
paste log output here
```
</details>

### Additional information:

- FlexGet version: 3.7.10
- Installation method: [Synocommunity package](https://synocommunity.com/package/flexget)
- OS and version: DSM 7.2.1-69057 (Synology DS218)
- Browser Version: Brave 1.64.109
