### ISSUE TITLE
[BUG] Variables cannot be saved with singles quotes around

### ISSUE THREAD

**Issue by junpet** [Flexget/webui#90]
### Expected behaviour:
Save variable url with folding `'` character (as suggested in the [documentation](https://flexget.com/Plugins/variables)). This works in `v1`.

### Actual behaviour:
You can't save a variable with `'` characters folding it. The variables won't be saved.
### Steps to reproduce:
- Step 1: Create a variable with an url value and fold it with `'` character.
- Step 2: Save it.
- Step 3: Reload the page. The `'` characters will be removed. Using the variable like this will generate a `CRITICAL`: `[/templates/gotify/notify/entries/via/0/gotify/url] '{? gotify.url ?}' is not a 'url'`

#### Config:
`variables`
```yaml
gotify:
  token: mytoken
  url: 'https://mydomain.org'
```
`config`
```yml
templates:
  gotify:
    notify:
      entries:
        via:
          - gotify:
              url: '{? gotify.url ?}'
              token: '{? gotify.token ?}'
```

#### Log:
<details>
 <summary>(click to expand)</summary>

```
[/templates/gotify/notify/entries/via/0/gotify/url] '{? gotify.url ?}' is not a 'url'
```
</details>

### Additional information:

- FlexGet version: 3.1.15
- Installation method: Docker
- OS and version: Debian 10
- Browser Verson: Firefox 72.0.2

**Comment by kristenmills** [comment]
This has nothing to do with single quotes. The quotes are not required in yaml so when converting from json to yaml, they won't be rendered. 

Do you mind posting your full config? Do you have `variables: variables.yml` at the top of the file?

**Comment by kristenmills** [comment]
Also this is the same issue as the one you posted over on main repo https://github.com/Flexget/Flexget/issues/2592. So closing this as duplicate.

**Comment by junpet** [comment]
This is not the same issue, as you can read both of issues.  I can't add the `variables: variables.yml ` line to my config, because `v1` won't save (`YAML Error`), and `v2` won't save the `config.yml` either. I've already wrote on the other repo as well. The problem is not in my `config.yml`. I've a working config for months. After inserting the one specific line I can't save it.

Again, this and the other issue is different. This issue happens only with `v2`. Please read my first post carefully again and open the issue. The other issue I've opened on the main repo is a problem with numbers, and associated with both `v1` and `v2`. That's why I've opened that there, because I think that's not associated with the webui, but its just a guess. Sorry for taking my time and reporting these issues, I'm trying my best.

**Comment by kristenmills** [comment]
Hi. I think you are misunderstanding. Based on the log of the errors, the root cause of both issues is likely to be the same. So to not fragment discussion, I want to close this issue so we can figure out what is causing both issues, over in main repo. It's either an issue with your config or an issue with the API. 

And just to reiterate, the single quotes thing is not an issue,
```yaml
gotify:
  token: mytoken
  url: 'https://mydomain.org'
```
is the exact same as 
```yaml
gotify:
  token: mytoken
  url: https://mydomain.org
```
The API converts json to yaml to display it and then yam to json to save it. So both results when you refresh will be without the single quotes.
